# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gym.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgym.proto\x12\x0blightweight\"\'\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x63tions\x18\x02 \x03(\t\"\"\n\x05Reply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t2@\n\x03Gym\x12\x39\n\x0c\x42odyBuilding\x12\x13.lightweight.Person\x1a\x12.lightweight.Reply\"\x00\x62\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'gym_pb2'
  # @@protoc_insertion_point(class_scope:lightweight.Person)
  })
_sym_db.RegisterMessage(Person)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'gym_pb2'
  # @@protoc_insertion_point(class_scope:lightweight.Reply)
  })
_sym_db.RegisterMessage(Reply)

_GYM = DESCRIPTOR.services_by_name['Gym']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PERSON._serialized_start=26
  _PERSON._serialized_end=65
  _REPLY._serialized_start=67
  _REPLY._serialized_end=101
  _GYM._serialized_start=103
  _GYM._serialized_end=167
# @@protoc_insertion_point(module_scope)
